name: Build with Self-Hosted

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, label-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test step
        run: echo "Running on my self-hosted runner 🚀"

      - name: List passwd file
        run: cat /etc/passwd
